theme: jekyll-theme-giellalt
title: Dictionary for Finnish ⇒ North Sámi
description: An electronic dictionary from Finnish to North Sámi

defaults:
  - scope: { path: "" }
    values:
      layout: default

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
